# Generated by Django 2.1.2 on 2018-10-23 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_auto_20181023_0913'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message_title',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='notice_title',
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.CharField(default='个人消息', max_length=20),
        ),
        migrations.AddField(
            model_name='notice',
            name='title',
            field=models.CharField(default='通知标题', max_length=20, verbose_name='通知标题'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='user.User'),
        ),
    ]
